name: "mirror workflow"

on:
  workflow_dispatch:

jobs:
  ngrok_ssh_tunnel:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: install requirements-cli
        run: pip3 install -r requirements-cli.txt; pip3 install -r requirements.txt
      #- name: copy config
        #run: cp config_sample.env config.env
      - name: copy config and delete the first line
        run: echo "BOT_TOKEN = $BOT_TOKEN" > config.env
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
      - run: echo "OWNER_ID = $OWNER_ID" >> config.env
        env:
          OWNER_ID: ${{ secrets.OWNER_ID }}
      - run: echo "TELEGRAM_API = $TELEGRAM_API" >> config.env
        env:
          TELEGRAM_API: ${{ secrets.TELEGRAM_API }}
      - run: echo "TELEGRAM_HASH = $TELEGRAM_HASH" >> config.env
        env:
          TELEGRAM_HASH: ${{ secrets.TELEGRAM_HASH }}
      - run: echo "USER_SESSION_STRING = $USER_SESSION_STRING" >> config.env
        env:
          USER_SESSION_STRING: ${{ secrets.USER_SESSION_STRING }}
      - run: tail -n +10 config_sample.env >> config.env
      - run: ./start.sh
