name: "mirror workflow"

on:
  workflow_dispatch:

jobs:
  ngrok_ssh_tunnel:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: install requirements-cli
        run: pip3 install -r requirements-cli.txt
      #- name: copy config
        #run: cp config_sample.env config.env
      - name: copy config and delete the first line
      - run: cat config.env
      - run: $BOT_TOKEN > config.env
      - run: $OWNER_ID >> config.env
      - run: $TELEGRAM_API >> config.env
      - run: $TELEGRAM_HASH >> config.env
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          OWNER_ID: ${{ secrets.OWNER_ID }}
          TELEGRAM_API: ${{ secrets.TELEGRAM_API }}
          TELEGRAM_HASH: ${{ secrets.TELEGRAM_HASH }}
      - run: tail -n +8 config_sample.env >> config.env
