name: "mirror workflow"

on:
  workflow_dispatch:

jobs:
  ngrok_ssh_tunnel:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: install requirements-cli
        run: pip3 install -r requirements-cli.txt
      #- name: copy config
        #run: cp config_sample.env config.env
      - name: copy config and delete the first line
        run: tail -n +3 config_sample.env > config.env
      - run: ./start.sh
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
      #- run: cat config.env
